### ISSUE TITLE
Retrieve external assets over HTTPS

### ISSUE THREAD

**Issue by esebastian** [VLCTechHub/VLCTechFest2017#16]
When accessing the site over HTTPS the browser expects all the external assets to be requested over HTTPS. If not, it blocks the request.

**Comment by jguitar** [comment]
You close the wrong issue with your commit c5c8c6687f4d45db6e6ae0df6b6423aabc852722

Maybe you can use the trick of "//domain.com/blahblah", instead of specify the protocol.

**Comment by esebastian** [comment]
Thanks @jguitar!

The idea with specifying the protocol is to force the use of HTTPS. That wouldn't be a problem even if we're using an HTTP connection.
