### ISSUE TITLE
Add the URL to project

### ISSUE THREAD

**Issue by jguitar** [VLCTechHub/VLCTechFest2017#3]
What about to add the URL to http://vlctechfest.org/ to the description?

**Comment by jguitar** [comment]
Now I reread my issue, I see that maybe it's a bit confusing.

I meant to add the URL of the webpage to the description of Github's project

**Comment by DavidHernandez** [comment]
I do not have access to do this change. @hell03610 or @esebastian can you do it or add me to the VlcTechHub team?

**Comment by esebastian** [comment]
@DavidHernandez You should have an invitation in your inbox.

I've added the info in the repo description.
